language: php

php:
  - 5.6

env:
  matrix:
    - ADAPTER=bar
    - ADAPTER=foo
    - ADAPTER=common

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:

before_install:

install:

script:

after_success:

sudo: false
