language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

# env:
#   matrix:
#     - ADAPTER=bar PHPUNIT_FILE=filepath
#     - ADAPTER=foo
#     - ADAPTER=common

matrix:
  include:
    - php: 5.6
      env: SEND_COVERAGE=true
    - php: 5.6
      env: SUBSPLIT=true
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - "$HOME/.composer/cache"

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" ]; then sh build/ssh.sh; fi
  - if [[ $TRAVIS_PHP_VERSION != hhvm && SEND_COVERAGE != true ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit -c phpunit.xml.dist

after_success:
#  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PHP_VERSION" = "7.0" ] && [ "$ADAPTER" = "common" ]; then sh .travis/subsplit.sh; fi;

sudo: true

notifications:
  email: false
