language: php

php:
  - 5.6

env:
  global:
    - "Kl1SMwD0vAMzVSI4gcgPi7K0ObDHivImq3AoZwjPtZmEERy58jVV4BIqG0bb/7zwb48hWJhChiOm2ZYYG9VLRoT/pAJMXZRpfNdV/t/pzJJGfUycJLYVTJxgTBOAMsvOUwBtYBk0h1uCt09yb0d4TaCXH17fVFBg3KJ5dRRHNrsgi9P1G9OrlaZBanESN09prjsj1S8cpmCrbfFkEwdqdwm2vi17YEWOGZt6YVLQLqKqpllPf093rRk6m37/W8ybmlmalxi2opORl5hsPsxpIrBeopg2/0c0KStXnxBJZCE1EjzrI56yTbmmKWwTge+LMjr/r5KFGjAH+SHLN3kz0ai/RIakoSABXr1YsmdxpapqJmfzoYCPsROBFU7mqAkPQ9jzwONk0gW36z8GAdwTKAvuxYSGfUNCd4RbN3p4/j9lObcFeRDTdBrpLo8dInP4u9bGqb8RjHKCfOTWtA0dJdvyE4R2n7QtRtgbwnYSca7uSl2xMv7EBaWNicJXe49trQ/YZBgpjQZdDbiSjqGdO75rsiB89e2As0Ia6rkiFVHiVJwMiSh6RP1Wopf9//8tEwts13/1nLIakS3VTdm7WgOpdG9mCTFY41muRvN2moCap2W2lqhaxTM1b8JSgUsQTGaIKXPhddSUU/1/jq6x6PDtQtadpkOmmVL4yKp65Vs="
  matrix:
    - ADAPTER=bar PHPUNIT_FILE=filepath
    - ADAPTER=foo
    - ADAPTER=common
  global:
    secure: Y5G4d3K6M7VOfkM0TBdJn79JQAeCk2UT9RHLz8Cx5FJLthuhiVE8A/LbzJI6dOLkg4EwZKdjMQz5b1yfRc3aKWWk6jpcwEQCb7+bL9bVPZQLs0i6R8cjiDEdMEOESZI0hW7YgNoNJwpDRw+JZauStAlk8H+0zSWDMUD1NJNJPfNAwc12tYWGPzr4r5Lo58CLUbOPpXy1WxhKkKwWnYqwt+dk287ZvYpPMc04ItbiaH3Fl6w+BGM45QsRcLTYOGHxILkOfsRo+U8UnXlLAWd26n2/xxvv/hUEQGJF9KGRjr1DOeiO4m5pJLRBuORG5/knbkg0otKX0Dka261HH4/iE6TXc/X6i5f0m7kTtOHeCXBXumQmjCdTGKvrWOmj25xLAEkCSVC0RvlzjtIpHvCFpt37D9ycs3VZEjoFdG9AInSt401i787gItW/G/qmLdu0QbuR4dfC4COKGzmigkaec26xoKEo1JQFVtOtXba8fWkSVYxH3S2Iiqfe/Cdmz4641/0zwZ1zV3JsQBbeSmdikEWmSBvEj1mi0XvQhMER1ut8HoVLlSBN7m725hRwezS2OOY4y1p2/TH/eYQBIB3VK3idBgOBhd93K8GjLXFHpnZwV65ARp3CLHatvGZz4+NLdzfKBjx8eijoyXaSItZlOVp34ty6HlH/qzdfAlV1hxM=
matrix:
  fast_finish: true

cache:
  directories:
    - "$HOME/.composer/cache"

before_script:
  - git clone https://github.com/dflydev/git-subsplit.git
  - cd git-subsplit && sudo sh ./install.sh
  - git config user.name "Travis-CI" && git config user.email "travis@cache.test" && git add
  - cd .. && sh build/split-faster.sh

before_install:

install:

script:

after_success:

sudo: true

notifications:
  email: false
