language: php

php:
  - 5.6

env:
  matrix:
    - ADAPTER=bar PHPUNIT_FILE=filepath
    - ADAPTER=foo
    - ADAPTER=common

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - git clone https://github.com/dflydev/git-subsplit.git
  - cd git-subsplit && sh ./install.sh
  - cd .. && sh build/split-faster.sh

before_install:

install:

script:

after_success:

sudo: false

notifications:
  email: false